### ISSUE TITLE
this is more dumb

### ISSUE THREAD

**Issue by cymcymcymcym** [genius-harry/college-accpetance-rate-prediction#1]
dumb
<img width="128" alt="c0392a63d107f862054a0c8897df024" src="https://github.com/user-attachments/assets/c1c5154d-682e-4b2f-8ae5-7cca5c476359">

**Comment by genius-harry** [comment]
you stupid

**Comment by cymcymcymcym** [comment]
![image](https://github.com/user-attachments/assets/211e8f0c-f74d-4b96-bd4b-47ee6e10155e)

**Comment by genius-harry** [comment]
6
